//! Compile-time model catalog hydrated from `models.dev` + `liter-llm` provider registry.
//!
//! The catalog is embedded at build time by `build.rs` as a JSON blob via `include_str!`.
//! It provides typed access to provider routing data, model capabilities, pricing,
//! and context limits — used by the [`ProviderRegistry`], model router, and admin UI.

use std::sync::LazyLock;

use serde::{Deserialize, Serialize};

/// Embedded provider catalog JSON, generated by `build.rs`.
const CATALOG_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/provider_catalog.json"));

/// Lazily-parsed catalog singleton.
static CATALOG: LazyLock<ModelCatalog> = LazyLock::new(|| {
    let providers: Vec<ProviderInfo> = serde_json::from_str(CATALOG_JSON).unwrap_or_else(|e| {
        tracing::error!(error = %e, "Failed to parse embedded provider catalog");
        Vec::new()
    });
    ModelCatalog { providers }
});

/// Top-level catalog containing all known providers and their models.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelCatalog {
    providers: Vec<ProviderInfo>,
}

impl ModelCatalog {
    /// Get a reference to the global catalog singleton.
    #[must_use]
    pub fn global() -> &'static Self {
        &CATALOG
    }

    /// All providers in the catalog.
    #[must_use]
    pub fn all_providers(&self) -> &[ProviderInfo] {
        &self.providers
    }

    /// Look up a provider by ID.
    #[must_use]
    pub fn provider(&self, id: &str) -> Option<&ProviderInfo> {
        self.providers.iter().find(|p| p.id == id)
    }

    /// Look up a specific model within a provider.
    #[must_use]
    pub fn model(&self, provider_id: &str, model_id: &str) -> Option<&ModelInfo> {
        self.provider(provider_id)
            .and_then(|p| p.models.iter().find(|m| m.id == model_id))
    }

    /// Find all models matching the given capability requirements.
    pub fn models_with_capabilities(
        &self,
        requirements: &CapabilityFilter,
    ) -> Vec<(&ProviderInfo, &ModelInfo)> {
        let mut results = Vec::new();
        for provider in &self.providers {
            for model in &provider.models {
                if requirements.matches(&model.capabilities, &model.limits) {
                    results.push((provider, model));
                }
            }
        }
        results
    }

    /// Total number of providers in the catalog.
    #[must_use]
    pub fn provider_count(&self) -> usize {
        self.providers.len()
    }

    /// Total number of models across all providers.
    #[must_use]
    pub fn model_count(&self) -> usize {
        self.providers.iter().map(|p| p.models.len()).sum()
    }
}

/// Provider information from the merged catalog.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ProviderInfo {
    /// Provider identifier (e.g., `"openai"`, `"anthropic"`).
    pub id: String,
    /// Human-readable display name.
    pub display_name: String,
    /// Default API base URL (if known).
    #[serde(default)]
    pub base_url: Option<String>,
    /// Authentication configuration.
    #[serde(default)]
    pub auth: Option<ProviderAuth>,
    /// Supported API endpoints.
    #[serde(default)]
    pub endpoints: Vec<String>,
    /// Model ID prefixes that route to this provider.
    #[serde(default)]
    pub model_prefixes: Vec<String>,
    /// Parameter mappings for non-standard API shapes.
    #[serde(default)]
    pub param_mappings: Option<serde_json::Value>,
    /// Models available from this provider (from models.dev).
    #[serde(default)]
    pub models: Vec<ModelInfo>,
    /// Source indicator (present only for models.dev-only providers).
    #[serde(default)]
    pub source: Option<String>,
}

/// Provider authentication configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderAuth {
    /// Auth type (e.g., `"bearer"`, `"api_key"`).
    #[serde(rename = "type")]
    pub auth_type: String,
    /// Environment variable containing the API key.
    pub env_var: Option<String>,
}

/// Model information from the catalog.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelInfo {
    /// Model identifier (e.g., `"gpt-4o"`, `"claude-sonnet-4"`).
    #[serde(default)]
    pub id: String,
    /// Human-readable name.
    #[serde(default)]
    pub name: String,
    /// Model family (e.g., `"gpt-4"`, `"claude-opus"`).
    #[serde(default)]
    pub family: Option<String>,
    /// Capability flags.
    #[serde(default)]
    pub capabilities: ModelCapabilities,
    /// Input/output modalities.
    #[serde(default)]
    pub modalities: Modalities,
    /// Context window and output limits.
    #[serde(default)]
    pub limits: ModelLimits,
    /// Pricing per 1M tokens.
    #[serde(default)]
    pub cost: Option<ModelCost>,
    /// Release date string.
    #[serde(default)]
    pub release_date: Option<String>,
    /// Whether model weights are openly available.
    #[serde(default)]
    pub open_weights: bool,
}

/// Model capability flags.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelCapabilities {
    /// Supports tool calling / function calling.
    #[serde(default)]
    pub tool_call: bool,
    /// Supports reasoning / chain-of-thought.
    #[serde(default)]
    pub reasoning: bool,
    /// Supports structured output (JSON mode).
    #[serde(default)]
    pub structured_output: bool,
    /// Supports file/image attachments.
    #[serde(default)]
    pub attachment: bool,
    /// Supports temperature parameter.
    #[serde(default)]
    pub temperature: bool,
    /// Supports streaming responses.
    #[serde(default)]
    pub streaming: bool,
}

/// Input/output modalities.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Modalities {
    /// Supported input types (e.g., `["text", "image", "pdf"]`).
    #[serde(default)]
    pub input: Vec<String>,
    /// Supported output types (e.g., `["text"]`).
    #[serde(default)]
    pub output: Vec<String>,
}

/// Context and output token limits.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelLimits {
    /// Maximum context window in tokens.
    #[serde(default)]
    pub context_window: u64,
    /// Maximum output tokens.
    #[serde(default)]
    pub max_output: u64,
}

/// Pricing per 1M tokens (in USD).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelCost {
    /// Input token cost per 1M.
    #[serde(default)]
    pub input: f64,
    /// Output token cost per 1M.
    #[serde(default)]
    pub output: f64,
    /// Cache read cost per 1M (if supported).
    #[serde(default)]
    pub cache_read: Option<f64>,
    /// Cache write cost per 1M (if supported).
    #[serde(default)]
    pub cache_write: Option<f64>,
}

impl ModelCost {
    /// Compute USD cost for a request given token counts. `cache_read_tokens` is
    /// the cached (read) portion already included in `input_tokens`; it is billed
    /// at `cache_read` when priced, otherwise at the regular input rate. Pure and
    /// catalog-independent so it is unit-testable.
    #[must_use]
    pub fn compute(&self, input_tokens: u64, output_tokens: u64, cache_read_tokens: u64) -> f64 {
        self.compute_with_cache_write(input_tokens, output_tokens, cache_read_tokens, 0)
    }

    /// Compute catalog-priced usage with disjoint cache read/write portions
    /// already included in `input_tokens`. Missing cache prices use the regular
    /// input rate, as with [`Self::compute`]; this remains a catalog estimate.
    #[must_use]
    #[expect(
        clippy::cast_precision_loss,
        reason = "token counts are far below f64's 2^52 exact-integer range"
    )]
    pub(crate) fn compute_with_cache_write(
        &self,
        input_tokens: u64,
        output_tokens: u64,
        cache_read_tokens: u64,
        cache_write_tokens: u64,
    ) -> f64 {
        const PER_M: f64 = 1_000_000.0;
        let cached = cache_read_tokens.min(input_tokens);
        let written = cache_write_tokens.min(input_tokens.saturating_sub(cached));
        let regular_input = input_tokens.saturating_sub(cached).saturating_sub(written);
        let cache_rate = self.cache_read.unwrap_or(self.input);
        let write_rate = self.cache_write.unwrap_or(self.input);
        (regular_input as f64) * self.input / PER_M
            + (cached as f64) * cache_rate / PER_M
            + (written as f64) * write_rate / PER_M
            + (output_tokens as f64) * self.output / PER_M
    }
}

/// Estimate USD cost for a `provider/model` request from the global pricing
/// catalog. Returns `None` when the model id is malformed, the model is absent
/// from the catalog, or the model has no pricing — callers treat `None` as
/// "cost unknown" (no error).
#[must_use]
pub fn estimate_cost(
    model: &str,
    input_tokens: u64,
    output_tokens: u64,
    cache_read_tokens: u64,
) -> Option<f64> {
    estimate_cost_with_cache_write(model, input_tokens, output_tokens, cache_read_tokens, 0)
}

/// Estimate catalog-priced usage including cache writes. Both cache counts are
/// portions of `input_tokens`. Returns `None` under the same conditions as
/// [`estimate_cost`]; cache duration-specific pricing is not represented here.
#[must_use]
pub(crate) fn estimate_cost_with_cache_write(
    model: &str,
    input_tokens: u64,
    output_tokens: u64,
    cache_read_tokens: u64,
    cache_write_tokens: u64,
) -> Option<f64> {
    let (provider, model_id) = model.split_once('/')?;
    let cost = ModelCatalog::global()
        .model(provider, model_id)?
        .cost
        .as_ref()?;
    Some(cost.compute_with_cache_write(
        input_tokens,
        output_tokens,
        cache_read_tokens,
        cache_write_tokens,
    ))
}

#[cfg(test)]
mod cost_tests {
    use super::{ModelCost, estimate_cost};

    fn approx(a: f64, b: f64) -> bool {
        (a - b).abs() < 1e-9
    }

    #[test]
    fn compute_input_output_no_cache() {
        // $3/1M input, $15/1M output.
        let cost = ModelCost {
            input: 3.0,
            output: 15.0,
            cache_read: None,
            cache_write: None,
        };
        // 1M input + 1M output = 3 + 15 = 18.
        assert!(approx(cost.compute(1_000_000, 1_000_000, 0), 18.0));
    }

    #[test]
    fn compute_applies_cache_read_discount() {
        let cost = ModelCost {
            input: 3.0,
            output: 15.0,
            cache_read: Some(0.30),
            cache_write: None,
        };
        // 1M input of which 1M cached at $0.30, 0 output = 0.30.
        assert!(approx(cost.compute(1_000_000, 0, 1_000_000), 0.30));
        // Half cached: 0.5M*3 + 0.5M*0.30 = 1.5 + 0.15 = 1.65.
        assert!(approx(cost.compute(1_000_000, 0, 500_000), 1.65));
    }

    #[test]
    fn compute_cache_falls_back_to_input_rate_when_unpriced() {
        let cost = ModelCost {
            input: 2.0,
            output: 0.0,
            cache_read: None,
            cache_write: None,
        };
        // No cache price → cached billed at input rate; 1M total = 2.0.
        assert!(approx(cost.compute(1_000_000, 0, 1_000_000), 2.0));
    }

    #[test]
    fn estimate_cost_unknown_model_is_none() {
        assert!(estimate_cost("nonexistent-provider/nope-model", 100, 100, 0).is_none());
    }

    #[test]
    fn estimate_cost_malformed_id_is_none() {
        assert!(estimate_cost("no-slash-here", 100, 100, 0).is_none());
    }
}

/// Filter for querying models by capability requirements.
#[derive(Debug, Clone, Default)]
pub struct CapabilityFilter {
    /// Model must support tool calling.
    pub needs_tools: bool,
    /// Model must support reasoning.
    pub needs_reasoning: bool,
    /// Model must support vision/image input.
    pub needs_vision: bool,
    /// Model must support structured output.
    pub needs_structured_output: bool,
    /// Minimum context window size.
    pub min_context: Option<u64>,
    /// Maximum input cost per 1M tokens.
    pub max_cost_per_1m_input: Option<f64>,
}

impl CapabilityFilter {
    pub(crate) fn matches(&self, caps: &ModelCapabilities, limits: &ModelLimits) -> bool {
        if self.needs_tools && !caps.tool_call {
            return false;
        }
        if self.needs_reasoning && !caps.reasoning {
            return false;
        }
        if self.needs_vision && !caps.attachment {
            return false;
        }
        if self.needs_structured_output && !caps.structured_output {
            return false;
        }
        if let Some(min_ctx) = self.min_context {
            if limits.context_window < min_ctx {
                return false;
            }
        }
        true
    }
}
