//! Compile-time model catalog hydrated from `models.dev` + `liter-llm` provider registry.
//!
//! The catalog is embedded at build time by `build.rs` as a JSON blob via `include_str!`.
//! It provides typed access to provider routing data, model capabilities, pricing,
//! and context limits — used by the [`ProviderRegistry`], model router, and admin UI.

use std::sync::LazyLock;

use serde::{Deserialize, Serialize};

/// Embedded provider catalog JSON, generated by `build.rs`.
const CATALOG_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/provider_catalog.json"));

/// Lazily-parsed catalog singleton.
static CATALOG: LazyLock<ModelCatalog> = LazyLock::new(|| {
    let providers: Vec<ProviderInfo> =
        serde_json::from_str(CATALOG_JSON).unwrap_or_else(|e| {
            tracing::error!(error = %e, "Failed to parse embedded provider catalog");
            Vec::new()
        });
    ModelCatalog { providers }
});

/// Top-level catalog containing all known providers and their models.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelCatalog {
    providers: Vec<ProviderInfo>,
}

impl ModelCatalog {
    /// Get a reference to the global catalog singleton.
    #[must_use]
    pub fn global() -> &'static Self {
        &CATALOG
    }

    /// All providers in the catalog.
    #[must_use]
    pub fn all_providers(&self) -> &[ProviderInfo] {
        &self.providers
    }

    /// Look up a provider by ID.
    #[must_use]
    pub fn provider(&self, id: &str) -> Option<&ProviderInfo> {
        self.providers.iter().find(|p| p.id == id)
    }

    /// Look up a specific model within a provider.
    #[must_use]
    pub fn model(&self, provider_id: &str, model_id: &str) -> Option<&ModelInfo> {
        self.provider(provider_id)
            .and_then(|p| p.models.iter().find(|m| m.id == model_id))
    }

    /// Find all models matching the given capability requirements.
    pub fn models_with_capabilities(
        &self,
        requirements: &CapabilityFilter,
    ) -> Vec<(&ProviderInfo, &ModelInfo)> {
        let mut results = Vec::new();
        for provider in &self.providers {
            for model in &provider.models {
                if requirements.matches(&model.capabilities, &model.limits) {
                    results.push((provider, model));
                }
            }
        }
        results
    }

    /// Total number of providers in the catalog.
    #[must_use]
    pub fn provider_count(&self) -> usize {
        self.providers.len()
    }

    /// Total number of models across all providers.
    #[must_use]
    pub fn model_count(&self) -> usize {
        self.providers.iter().map(|p| p.models.len()).sum()
    }
}

/// Provider information from the merged catalog.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderInfo {
    /// Provider identifier (e.g., `"openai"`, `"anthropic"`).
    pub id: String,
    /// Human-readable display name.
    pub display_name: String,
    /// Default API base URL (if known).
    #[serde(default)]
    pub base_url: Option<String>,
    /// Authentication configuration.
    #[serde(default)]
    pub auth: Option<ProviderAuth>,
    /// Supported API endpoints.
    #[serde(default)]
    pub endpoints: Vec<String>,
    /// Model ID prefixes that route to this provider.
    #[serde(default)]
    pub model_prefixes: Vec<String>,
    /// Parameter mappings for non-standard API shapes.
    #[serde(default)]
    pub param_mappings: Option<serde_json::Value>,
    /// Models available from this provider (from models.dev).
    #[serde(default)]
    pub models: Vec<ModelInfo>,
    /// Source indicator (present only for models.dev-only providers).
    #[serde(default)]
    pub source: Option<String>,
}

/// Provider authentication configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderAuth {
    /// Auth type (e.g., `"bearer"`, `"api_key"`).
    #[serde(rename = "type")]
    pub auth_type: String,
    /// Environment variable containing the API key.
    pub env_var: Option<String>,
}

/// Model information from the catalog.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelInfo {
    /// Model identifier (e.g., `"gpt-4o"`, `"claude-sonnet-4"`).
    #[serde(default)]
    pub id: String,
    /// Human-readable name.
    #[serde(default)]
    pub name: String,
    /// Model family (e.g., `"gpt-4"`, `"claude-opus"`).
    #[serde(default)]
    pub family: Option<String>,
    /// Capability flags.
    #[serde(default)]
    pub capabilities: ModelCapabilities,
    /// Input/output modalities.
    #[serde(default)]
    pub modalities: Modalities,
    /// Context window and output limits.
    #[serde(default)]
    pub limits: ModelLimits,
    /// Pricing per 1M tokens.
    #[serde(default)]
    pub cost: Option<ModelCost>,
    /// Release date string.
    #[serde(default)]
    pub release_date: Option<String>,
    /// Whether model weights are openly available.
    #[serde(default)]
    pub open_weights: bool,
}

/// Model capability flags.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelCapabilities {
    /// Supports tool calling / function calling.
    #[serde(default)]
    pub tool_call: bool,
    /// Supports reasoning / chain-of-thought.
    #[serde(default)]
    pub reasoning: bool,
    /// Supports structured output (JSON mode).
    #[serde(default)]
    pub structured_output: bool,
    /// Supports file/image attachments.
    #[serde(default)]
    pub attachment: bool,
    /// Supports temperature parameter.
    #[serde(default)]
    pub temperature: bool,
    /// Supports streaming responses.
    #[serde(default)]
    pub streaming: bool,
}

/// Input/output modalities.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Modalities {
    /// Supported input types (e.g., `["text", "image", "pdf"]`).
    #[serde(default)]
    pub input: Vec<String>,
    /// Supported output types (e.g., `["text"]`).
    #[serde(default)]
    pub output: Vec<String>,
}

/// Context and output token limits.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelLimits {
    /// Maximum context window in tokens.
    #[serde(default)]
    pub context_window: u64,
    /// Maximum output tokens.
    #[serde(default)]
    pub max_output: u64,
}

/// Pricing per 1M tokens (in USD).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelCost {
    /// Input token cost per 1M.
    #[serde(default)]
    pub input: f64,
    /// Output token cost per 1M.
    #[serde(default)]
    pub output: f64,
    /// Cache read cost per 1M (if supported).
    #[serde(default)]
    pub cache_read: Option<f64>,
    /// Cache write cost per 1M (if supported).
    #[serde(default)]
    pub cache_write: Option<f64>,
}

/// Filter for querying models by capability requirements.
#[derive(Debug, Clone, Default)]
pub struct CapabilityFilter {
    /// Model must support tool calling.
    pub needs_tools: bool,
    /// Model must support reasoning.
    pub needs_reasoning: bool,
    /// Model must support vision/image input.
    pub needs_vision: bool,
    /// Model must support structured output.
    pub needs_structured_output: bool,
    /// Minimum context window size.
    pub min_context: Option<u64>,
    /// Maximum input cost per 1M tokens.
    pub max_cost_per_1m_input: Option<f64>,
}

impl CapabilityFilter {
    fn matches(&self, caps: &ModelCapabilities, limits: &ModelLimits) -> bool {
        if self.needs_tools && !caps.tool_call {
            return false;
        }
        if self.needs_reasoning && !caps.reasoning {
            return false;
        }
        if self.needs_structured_output && !caps.structured_output {
            return false;
        }
        if let Some(min_ctx) = self.min_context {
            if limits.context_window < min_ctx {
                return false;
            }
        }
        true
    }
}
