StylesPath = .github/styles
MinAlertLevel = suggestion
Vocab = UAR

[*.md]
BasedOnStyles = UAR

# Project-specific terminology
[*.md]
UAR.Terms = yes
UAR.Inclusive = yes
UAR.Acronyms = yes

[formats]
mdx = md
