-- SUPERSEDED: This migration is intentionally a no-op.
--
-- The canonical settings schema (settings_types + settings tables with
-- parent_id, created_at, updated_at, triggers, and all indexes) is defined
-- in migration 0010_settings_tables.sql, which runs before this file
-- lexicographically and uses CREATE TABLE IF NOT EXISTS.
--
-- This file originally defined a conflicting schema (missing parent_id,
-- missing created_at/updated_at on settings_types, extra columns
-- description/display_mode/icon_url that the Rust code does not use).
-- It has been emptied to prevent any future confusion or schema drift.
--
-- DO NOT add DDL here. All schema changes go through numbered migrations.
