apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uar.fullname" . }}-config
  namespace: {{ include "uar.namespace" . }}
  labels:
    {{- include "uar.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.uar.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
