apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uar.fullname" . }}-secrets
  namespace: {{ include "uar.namespace" . }}
  labels:
    {{- include "uar.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.uar.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
