apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uar.fullname" . }}-app
  namespace: {{ include "uar.namespace" . }}
  labels:
    {{- include "uar.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
