import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The docs sidebar is autogenerated from the `docs/` folder. The order of the
 * top-level sections is controlled by each folder's `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
